#_welcome:
#    pattern:  /
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: get_servers
#        permanent: true # this for 301

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

servers_api:
    resource: FormaLibre\RestBundle\Controller\ServerController
    type:     rest

platforms_api:
    resource: FormaLibre\RestBundle\Controller\PlatformController
    type:     rest

clients_api:
    resource: FormaLibre\RestBundle\Controller\ClientController
    type:     rest

events_api:
    resource: FormaLibre\RestBundle\Controller\EventController
    type:     rest
