services:
  forma_libre.rest_bundle.server_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine", getRepository]
    arguments:
      - FormaLibre\RestBundle\Entity\Server

  forma_libre.rest_bundle.server_manager:
    class: FormaLibre\RestBundle\Manager\ServerManager
    arguments:
      - '@forma_libre.rest_bundle.server_repository'
      - '@forma_libre.rest_bundle.form.handler.server_form_handler'

  forma_libre.rest_bundle.form.type.server:
    class: FormaLibre\RestBundle\Form\Type\ServerType
    tags:
      - { name: form.type, alias: server_form }

  forma_libre.rest_bundle.form.handler.server_form_handler:
    class: FormaLibre\RestBundle\Form\Handler\FormHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@form.factory'
      - '@forma_libre.rest_bundle.form.type.server'
