#_welcome:
#    pattern:  /
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: get_servers
#        permanent: true # this for 301

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

api:
    type: rest
    resource: "routing_api.yml"
